name: mycycleclinic
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  nb_utils: ^5.0.8
  intl: ^0.17.0
  flutter_vector_icons: 1.0.0
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  email_validator: ^2.0.1

  cached_network_image: ^3.2.2
  cloud_firestore: ^4.7.1
  hive: ^2.2.3
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.0.5

flutter_native_splash:
  color: "#000000"
  image: assets/images/logo.png

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/app/
    - assets/images/beauty_master/
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
